# @package eval.tofu.metrics.mia_loss
defaults:
  - ../../data/datasets@datasets: TOFU_MIA
  - ../../collator@collators: DataCollatorForSupervisedDatasetwithIndex
batch_size: ${eval.tofu.batch_size}
handler: mia_loss

datasets:
  TOFU_QA_forget:
    args:
      hf_args:
        name: ${eval.tofu.forget_perturbed_split}
      question_key: ${eval.tofu.question_key}
  TOFU_QA_holdout:
    args:
      hf_args:
        name: ${eval.tofu.holdout_split}
