# @package eval.duet.metrics.forget_qa_rouge
defaults:
  - ../../data/datasets@datasets: DUET_QA_forget
  - ../../collator@collators: DataCollatorForSupervisedDatasetwithIndex
  - ../../generation@generation_args: default

handler: rouge
rouge_type: rougeL_recall #rougeL_f1
batch_size: ${eval.duet.batch_size}

generation_args:
  max_new_tokens: 64

datasets:
  DUET_QA_forget:
    args:
      hf_args:
        split: ${eval.duet.forget_split}
      question_key: ${eval.duet.question_key}
      predict_with_generate: True
collators:
  DataCollatorForSupervisedDataset: 
    args:
      padding_side: left
